swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Go swagger samples'
basePath: '/v1'
paths:
  /hello:
    get:
      description: 'hello world'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      responses:
        '405':
          description: 'Invalid input'
        '200':
          description: 'successful operation'
          schema:
            $ref: '#/definitions/ApiResponse'
definitions:
  ApiResponse:
    type: 'object'
    properties:
      code:
        type: 'integer'
        format: 'int32'
      type:
        type: 'string'
      message:
        type: 'string'
